//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incidence()
        {
            this.Documents = new HashSet<Document>();
            this.RelationIncidenceCustomers = new HashSet<RelationIncidenceCustomer>();
        }
    
        public int idIncidence { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int idState { get; set; }
        public int idEnvironment { get; set; }
        public int idLocal { get; set; }
        public int idUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual Local Local { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationIncidenceCustomer> RelationIncidenceCustomers { get; set; }
    }
}
